terragrunt_version: "v0.23.35"
terragrunt_binary: terragrunt_linux_amd64

packer_version: "1.6.1"
packer_binary: linux_amd64

terraform_docs_version: "v0.9.1"
terraform_docs_binary: linux-amd64

tflint_version: "0.19.1"
tflint_binary: linux_amd64
